### ISSUE TITLE
New-XIOLunMap Hangs with version 4.x

### ISSUE THREAD

**Issue by nniehoff** [mtboren/XtremIO.Utils#3]
When I run a New-XIOLunMap against an array with version 4.0 of the EMC code the command hangs and never completes.

**Comment by mtboren** [comment]
Hello, @nniehoff -

On what XIOS version specifically are you seeing this?  You can get the `SWVersion` of the XMS to which you are connected by using `Get-XIOXMS`, or you can inspect the `$DefaultXmsServers` variable (the property there is (`XmsSWVersion`).  Say, by piping the variable to `Format-List` like:
`$DefaultXmsServers | Format-List *`

It should be a value like "4.0.1-41".  I ask because that is the XIOS version against which I tested, and the call did not hang.

Another question:  to how many XMSs are you connected (via `Connect-XIOServer`) when issuing the `New-XIOLunMap` command?

**Comment by nniehoff** [comment]
I am on 4.0.1-r1_hotfix_1, it’s pretty new… I am connected to one XMS.  I noticed it get slower when we moved to version 4, and it seems like it has gotten slower and slower the more volumes/hosts we have.  We currently have 203 Volumes and 34 hosts, most volumes are mapped to all hosts.  I would have to say we did use the New-XIOLunMap command on previous versions of 4.x but we recently upgraded to hotfix1 as we were experiencing a known issue without it.

Nick

**Comment by mtboren** [comment]
Ok, then, thanks for the info.  Yes, the `Get-XIOLunMap` cmdlet performance can definitely lag, since `LunMap` objects are one of the most plentiful on an array (one object for every LUN -> InitiatorGroup mapping, of course).  The `New-XIOLunMap` cmdlet leverages the `Get-XIOLunMap` cmdlet one time before trying to create the new `LunMap` (to make sure that such a `LunMap` does not already exist for the Volume/InitiatorGroup pair).

How long does just doing a `Get-XIOLunMap` take when you are connected to this XMS?  Like:
`Measure-Command {Get-XIOLunMap}`

Or, does that ever return, either?

Yet another question:  when you invoke the `New-XIOLunMap` call, do any of the LUN mappings get created, or the process never even seems to start creating them?

I don't have access to an array with that hotfix version to test. But, a possible interim "fix" (workaround) might be for us to modify the `New-XIOLunMap` cmdlet to have an "expert" or "no-check" mode in which the cmdlet does not check for an existing `LunMap`.

Let me know

**Comment by nniehoff** [comment]
It took 8.34 minutes to run get-xiolunmap.  Today we added 1 host, I created 1 Volume as it’s boot LUN and when I tried to create the lunmap I waited a very long time (ok I don’t have the best patience in the world), it seemed like an hour but was probably more like 15 minutes before I canceled the command.  It seemed like it was never going to return.  I like the idea of an expert command, but I don’t know what the array does if you tell it to create a lunmap that already exists unfortunately this is my production array so I’m not really eager to go try it either.

Thanks,
Nick

**Comment by nniehoff** [comment]
I just looked at the EMC REST API guide, wow, getting the lun-maps just sucks from the EMC side, there is no way to filter that query at all from the array.  I wonder if you could cache that information in the module so you only have to get it once?

**Comment by mtboren** [comment]
Roger that -- then I'll not invest any time in "pro mode".

And, yes -- the API can been a bit inefficient when dealing with large numbers of objects, since the "view" has been a list of HREFs for each object, and then one needs to use each HREF for another web call.

But, in v2 of the API, EMC made some grand improvements, one of which provides the ability to get objects' info in one call overall, instead of one call per object.  I am working to add support for using this feature for getting objects from XIOConnections to XMSs with v2 of the API.  This should help quite a bit with the speed issue, and we should be able to solve this without leveraging caching mechanisms.  I'll push updates when they're ready.

**Comment by mtboren** [comment]
Hello-

I added support for using that XIO REST APIv2 feature (code determines if the REST API is at least v2 before trying to use it), and updated `Get-XIOLunMap` to use this improved feature.  The update is in commit 04837f570144706a36db413bad784800e2374c89, which I have now merged into the `dev` branch and pushed up to GitHub.

You can test the new feature by grabbing the `dev` branch zip file, unpacking and importing the module, and then checking out the performance via `Measure-Command` on `Get-XIOLunMap`.

And, there are other optimizations to add to the module that the newer XIO API enables, but I want to make sure that this part is right, first.

Let me know if that is better (faster) than with the previous version of the module, won't you?

**Comment by nniehoff** [comment]
I got a failure:

VERBOSE: Uh-oh -- something went awry trying to get data from that URI ('https://X.X.X.X/api/json/types/lun-maps?full=1')
VERBOSE: no additional web exception response value to report
ConvertFrom-Json : Error during serialization or deserialization using the JSON JavaScriptSerializer. The length of the string exceeds the value set on the
maxJsonLength property.
Parameter name: input
At C:\Users\nick.niehoff\Downloads\XtremIO.Utils-dev\XtremIO.Utils\XIO_SupportingFunctions.ps1:58 char:62
-             $oWebClient.DownloadString($hshParamsForRequest["Uri"]) | ConvertFrom-Json
-                                                                       ~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
  - FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

**Comment by mtboren** [comment]
Hello, @nniehoff -

Of course -- there's always something.  The something here is apparently the hard 2MB limit for the `maxJsonLength` property used internally in the `ConvertFrom-Json` cmdlet.  The options to work around this were either:
0.  handle the conversion from JSON manually
1.  decrease the size of the JSON response being retrieved

As one of the eventual goals in the todo list for this module was to allow for the latter, I created a branch in which I started support for such a feature, by allowing for specifying select properties to retrieve, instead of the default behavior that retrieves all properties.  Support is not completely implemented yet, but is in there for the `Get-XIOLunMap` cmdlet now, and I updated the `New-XIOLunMap` cmdlet to leverage this feature.  The update is in commit 4b7062e3ca5a926b0a2774d86e67357fc88f15f7, which is in branch `feat_SpecifyProperties`.

When you have time, please try out this version of the module.  Of course, we all want `New-XIOLunMap` to actually work.  But also, try out `Get-XIOLunMap` with its initial `-Property` support:

`Get-XIOLunMap -Verbose -Property name,lun,vol-name`

That gets just the three specified properties along with a few standard properties that will always get returned.  Also, this should include a Verbose message about the size of the JSON that is being retrieved, something like, "VERBOSE: [Get-XIOInfo] API reply JSON length (KB): 52.919".

So:
0)  does `Get-XIOLunMap` get LunMap objects now?
1)  if so, what is the size of the JSON that the verbose message reports?
2)  and, if so, how does `New-XIOLunMap` now do?

Matt

**Comment by nniehoff** [comment]
Matt,
   Sorry for the delay I forgot to give this a shot.  I realized we deleted a TON of LunMaps between this time and the last time so I downloaded the master branch again and did a measure on the get-xiolunmap, it now returns in 5.58 minutes.  I will add the output of the verbose command momentarily from the feat branch.

Nick

**Comment by nniehoff** [comment]
> Measure-Command { Get-XIOLunMap -Verbose -Property name,lun,vol-name}
> VERBOSE: [Get-XioConnectionsToUse] continuing with call, using '1' XIO connection
> VERBOSE: [New-XioApiURI] URI to use: 'https://X.X.X.X/api/json/types/lun-maps?full=1&prop=name&prop=lun&prop=vol-name'
> VERBOSE: [Get-XIOInfo] setting ServerCertificateValidationCallback method temporarily so as to 'trust' certs (should only be used if certs are known-good /
> trustworthy)
> VERBOSE: [Get-XIOInfo] API reply JSON length (KB): 679.571
> VERBOSE: [Get-XIOInfo] set ServerCertificateValidationCallback back to original value of 'System.Net.Security.RemoteCertificateValidationCallback'

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 3
Milliseconds      : 39
Ticks             : 30397162
TotalDays         : 3.5181900462963E-05
TotalHours        : 0.000844365611111111
TotalMinutes      : 0.0506619366666667
TotalSeconds      : 3.0397162
TotalMilliseconds : 3039.7162

**Comment by nniehoff** [comment]
Sorry I am switching between machines here.  Get-XIOLunMap by it self still returns the same error without the Properties option.  Looks like if I use -Verbose the JSON length is 3933.697KB.

**Comment by mtboren** [comment]
Hello-

Thx for the testing and the info.  So, a few observations:
0)  the use of the new capabilities of the REST API clearly help with reply speed and size
1)  until such a time that ConvertFrom-Json supports JSON of sizes larger than 2MB, we will either need to write a JSON handler, or leverage the `-Property` parameter to whittle down the amount of data returned from API calls

I will work to integrate these recent changes into the main branch.  Meanwhile, did you get to test the `New-XIOLunMap` cmdlet from the feat branch?  It leverages the `-Property` param and optimized API call to check for existing LunMaps for the given volume and initiator group, and should hit neither the "super long runtime" nor the "too big of JSON reply to handle" issues that you are seeing with the other versions.

And, man -- 4MB of JSON returned for your LunMap info -- that's a lot of LunMaps (like you already said)!

**Comment by nniehoff** [comment]
Sorry I didn't get back to you sooner.  I finally had the chance to create some more lun maps.  I just created 250 lun maps in approximately 3 minutes which is a huge improvement.

**Comment by nniehoff** [comment]
Didn't mean to close the issue.

**Comment by nniehoff** [comment]
So I actually needed to create a lot more lun maps, here are some better numbers.  I created LUN Maps for 134 LUNs on 8 Initiator Groups Totalling 1072 LunMaps.  This took:

Ticks             : 11757310713
Days              : 0
Hours             : 0
Milliseconds      : 731
Minutes           : 19
Seconds           : 35
TotalDays         : 0.0136079985104167
TotalHours        : 0.32659196425
TotalMilliseconds : 1175731.0713
TotalMinutes      : 19.595517855
TotalSeconds      : 1175.7310713

This is much much better than the old numbers.

**Comment by mtboren** [comment]
250 LunMaps in ~3 min -- that's better.  And, this most recent test with 1072 LunMaps in ~20 min -- not the greatest, but better than the old numbers, you say -- great.

A couple of question:
0.  with what version/branch of the module did you get these numbers?
1.  when issuing those `New-XIOLunMap` commands, are you doing one per LUN/IG pair (so, 1072 total `New-XIOLunMap` calls), or, one per LUN and including all of the desired IGs in that call (so, 134 total `New-XIOLunMap` calls)?  Just wanting to be sure that you are aware of the ability to specify an array of IGs in a single `New-XIOLunMap` call, and that you are leveraging that.

A touch more info:  while specifying the array of IGs for the new LunMap should speed up the overall run time, this time savings comes from the reduction of the number of "check for existing LunMaps for the given LUN/IG" calls that are made -- one per LUN, instead of one per LunMap.

**Comment by nniehoff** [comment]
I used the branch feat_SpecifyProperties from roughly 12/18.  I'm not sure which version exactly.  I believe the script I ran was running 134 total calls passing multiple groups at a time to the New-XIOLunMap function.
